on:
  schedule:
  - cron: "00 12 * * *"
  - cron: "00 00 * * *"
  
  push:
    branches:
      - main

jobs:
  get_adresses:
    name: get addresses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0     
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm install
      - name: Run code
        env:
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_SPREED_SHEET: ${{ secrets.GOOGLE_SPREED_SHEET }}
        run: node index.js
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
